"""Criar tabelas iniciais

Revision ID: 6b0ef88eec38
Revises: 
Create Date: 2024-03-09 20:14:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0ef88eec38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Criar tabela de veículos
    op.create_table(
        'veiculos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('placa', sa.String(length=7), nullable=False),
        sa.Column('cpf', sa.String(length=11), nullable=False),
        sa.Column('nome', sa.String(length=100), nullable=False),
        sa.Column('modelo', sa.String(length=50), nullable=False),
        sa.Column('tipo', sa.String(length=20), nullable=False),
        sa.Column('bloco', sa.String(length=10), nullable=True),
        sa.Column('apartamento', sa.String(length=10), nullable=True),
        sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
        sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('placa')
    )
    op.create_index(op.f('ix_veiculos_placa'), 'veiculos', ['placa'], unique=True)

    # Criar tabela de vagas
    op.create_table(
        'vagas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('numero', sa.Integer(), nullable=False),
        sa.Column('tipo', sa.String(length=20), nullable=False),
        sa.Column('ocupada', sa.Boolean(), nullable=False, default=False),
        sa.Column('veiculo_id', sa.Integer(), nullable=True),
        sa.Column('entrada', sa.DateTime(timezone=True), nullable=True),
        sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
        sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('numero')
    )
    op.create_index(op.f('ix_vagas_numero'), 'vagas', ['numero'], unique=True)

    # Criar tabela de funcionários
    op.create_table(
        'funcionarios',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=100), nullable=False),
        sa.Column('matricula', sa.String(length=4), nullable=False),
        sa.Column('ativo', sa.Boolean(), nullable=False, default=True),
        sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
        sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('matricula')
    )
    op.create_index(op.f('ix_funcionarios_matricula'), 'funcionarios', ['matricula'], unique=True)

    # Criar tabela de histórico
    op.create_table(
        'historico',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('acao', sa.String(length=50), nullable=False),
        sa.Column('placa', sa.String(length=7), nullable=False),
        sa.Column('nome', sa.String(length=100), nullable=False),
        sa.Column('tipo', sa.String(length=20), nullable=False),
        sa.Column('vaga_numero', sa.Integer(), nullable=True),
        sa.Column('tempo_min', sa.Integer(), nullable=True),
        sa.Column('funcionario_nome', sa.String(length=100), nullable=False),
        sa.Column('matricula', sa.String(length=4), nullable=False),
        sa.Column('data_evento', sa.DateTime(timezone=True), nullable=False),
        sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
        sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_placa'), 'historico', ['placa'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historico_placa'), table_name='historico')
    op.drop_table('historico')
    op.drop_index(op.f('ix_funcionarios_matricula'), table_name='funcionarios')
    op.drop_table('funcionarios')
    op.drop_index(op.f('ix_vagas_numero'), table_name='vagas')
    op.drop_table('vagas')
    op.drop_index(op.f('ix_veiculos_placa'), table_name='veiculos')
    op.drop_table('veiculos')
    # ### end Alembic commands ###